### PR TITLE
Upgrade htmlparser2 to version 6

### PR DESCRIPTION
**Pull request by realityking**
Test continue to pass. I'm mainly after this for the deduplication with other libraries :)

### CODE REVIEW

**Comment by realityking** [comment]
@KillyMXI @mlegenhausen Could you have a look at this one please? 🙏

**Comment by KillyMXI** [comment]
Sorry for the delay. I will try to get back to code in a few days.

**Comment by KillyMXI** [comment]
htmlparser2 jumps 2 major versions for a reason. While this doesn't affect the basic case, it might affect some users.
So I think it's a good time to address all small things that require the major version bump. The progress will be tracked in #222.

**Comment by realityking** [comment]
Makes sense. Thanks for merging. I’ll see if I can pick up some things from #222 to help move this along.

**Comment by KillyMXI** [comment]
There are things that are either trivial, done in my local copy or require my close attention anyway. So no need to worry.
If anything, #215 might be the one to pick up.

**Pull request merged**
